name: Windows-mingw
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/win-msvc.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/win-msvc.yml'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_arch: [mingw64_qt5, mingw32_qt5]
        include:
          - qt_arch: mingw64_qt5
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
          - qt_arch: mingw32_qt5
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
    env:
      targetName: corednshome
      
    steps:
      - uses: numworks/setup-msys2@v1
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          
      - run: msys2do pacman --noconfirm -S ${{ matrix.mingw_prefix }}-gcc ${{ matrix.mingw_prefix }}-clang ${{ matrix.mingw_prefix }}-make ${{ matrix.mingw_prefix }}-qt5 
                              
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      
      - run: mkdir build-gcc
      - run: mkdir build-clang
          
      - name: qmake-gcc
        shell: cmd
        run: |
          cd build-gcc
          msys2do qmake.exe -r -spec win32-g++ CONFIG+=release CONFIG+=qtquickcompiler ..
          cd ..

      - name: mingw32-make-gcc
        shell: cmd
        run: |
          cd build-gcc
          msys2do mingw32-make.exe -j 4
          cd ..
          
      - name: qmake-clang
        shell: cmd
        run: |
          cd build-clang
          msys2do qmake.exe -r -spec win32-clang-g++ CONFIG+=release CONFIG+=qtquickcompiler ..
          cd ..

      - name: mingw32-make-clang
        shell: cmd
        run: |
          cd build-clang
          msys2do mingw32-make.exe -j 4
          cd ..
          
      - name: deploy-gcc
        env:
          archiveName: ${{ env.targetName }}-Win-gcc
        shell: pwsh
        run: |
          New-Item -ItemType Directory ${env:archiveName}
          Copy-Item build-gcc\src\release\${env:targetName}'.exe' ${env:archiveName}\
          msys2do windeployqt.exe ${env:archiveName}/${env:targetName}'.exe'
          
      - name: deploy-clang
        env:
          archiveName: ${{ env.targetName }}-Win-clang
        shell: pwsh
        run: |
          New-Item -ItemType Directory ${env:archiveName}
          Copy-Item build-clang\src\release\${env:targetName}'.exe' ${env:archiveName}\
          msys2do windeployqt.exe ${env:archiveName}/${env:targetName}'.exe'

      - name: upload artifact-gcc
        uses: actions/upload-artifact@v1
        env:
          archiveName: ${{ env.targetName }}-Win-gcc
        with:
          path: ${{ env.archiveName }}
          name: ${{ env.targetName }}-${{ matrix.mingw_prefix }}-gcc

      - name: upload artifact-clang
        uses: actions/upload-artifact@v1
        env:
          archiveName: ${{ env.targetName }}-Win-clang
        with:
          path: ${{ env.archiveName }}
          name: ${{ env.targetName }}-${{ matrix.mingw_prefix }}-clang
