name: Windows-mingw
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/win-msvc.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/win-msvc.yml'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.14.2]
        qt_target: [desktop]
        qt_arch: [win64_mingw73, win32_mingw73]
        include:
          - qt_arch: win64_mingw73
            msvc_arch: x64
            arch: 64
            qt_arch_install: mingw73
          - qt_arch: win32_mingw73
            msvc_arch: x86
            arch: 32
            qt_arch_install: mingw73
    env:
      targetName: corednshome
      
    steps:
      - name: Cache msys2
        id: cache-msys2
        uses: actions/cache@v1
        with:
          path: msys${{ matrix.arch }}
          key: msys2-x${{ matrix.arch }}
      - name: Install msys2
        if: steps.cache-msys2.outputs.cache-hit != 'true'
        run: |
          if ( "${{ matrix.arch }}" -eq "32" ) {
            (New-Object net.webclient).DownloadFile("http://repo.msys2.org/distrib/i686/msys2-base-i686-20190524.tar.xz","msys2.tar.xz")
          } else {
            (New-Object net.webclient).DownloadFile("http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20190524.tar.xz","msys2.tar.xz")
          }
          tar xf msys2.tar.xz -C $env:GITHUB_WORKSPACE.Replace("\", "/")
      - run: |
          $env:MSYSTEM = "MINGW${{ matrix.arch }}"
          $env:MSYS2_PATH_TYPE = "strict"
          $script = @'
            uname -m
            uname -a
            echo $PATH
          '@
          & "$env:GITHUB_WORKSPACE\msys${{ matrix.arch }}\usr\bin\bash" -c -l $script
      - name: Pacman
        run: |
          $env:MSYSTEM = "MINGW${{ matrix.arch }}"
          $env:MSYS2_PATH_TYPE = "strict"
          $script = @'
            # pacman --noconfirm -Syu
            pacman --noconfirm -S msys/gcc
            if [ "$MSYSTEM" = "MINGW32" ]; then
              pacman --noconfirm -S mingw32/mingw-w64-i686-gcc mingw32/mingw-w64-i686-clang
            else
              pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-clang
            fi
            pacman --noconfirm -S make
          '@
          & "$env:GITHUB_WORKSPACE\msys${{ matrix.arch }}\usr\bin\bash" -c -l $script
          
      - name: upgrade pip
        shell: cmd
        run: |
          python.exe -m pip install --upgrade pip
          
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-${{ matrix.qt_ver }}-QtCache
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
          
      - name: build-mingw
        shell: cmd
        run: |
          $env:MSYSTEM = "MINGW${{ matrix.arch }}"
          $env:MSYS2_PATH_TYPE = "strict"
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ..\${{ env.targetName }}.pro
          make -j 4
          cd ..

      # tag 打包
      - name: deploy
        env:
          archiveName: CoreDNSHome-Win
        shell: pwsh
        run: |
          dir
          New-Item -ItemType Directory ${env:archiveName}
          dir
          dir build
          dir build\src
          dir build\src\release
          Copy-Item build\src\release\*.exe ${env:archiveName}\
          Copy-Item build\src\release\*.dll ${env:archiveName}\
          Copy-Item build\src\release\*.manifest ${env:archiveName}\
          dir ${env:archiveName}
          windeployqt.exe --qmldir . ${env:archiveName}\${env:targetName}'.exe'
          lrelease src\corednshome_zh-CN.ts
          Copy-Item src\corednshome_zh-CN.qm ${env:archiveName}\translations\

      - name: upload artifact
        uses: actions/upload-artifact@v1
        env:
          archiveName: CoreDNSHome-Win
        with:
          path: CoreDNSHome-Win
          name: CoreDNSHome-mingw-${{ matrix.msvc_arch }}

      # tag 打包
      - name: package
        if: startsWith(github.event.ref, 'refs/tags/')
        env:
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
          archiveName: ${{ env.targetName }}-${{ matrix.qt_arch }}
        shell: pwsh
        run: |
          # 打包zip
          Compress-Archive -Path CoreDNSHome-Win ${env:archiveName}'.zip'
          # 记录环境变量packageName给后续step
          $name = ${env:archiveName}
          echo "::set-env name=packageName::$name"
          # 打印环境变量packageName
          Write-Host 'packageName:'${env:packageName}
      # tag 查询github-Release
      - name: queryReleaseWin
        id: queryReleaseWin
        if: startsWith(github.event.ref, 'refs/tags/')
        shell: pwsh
        env:
          githubFullName: ${{ github.event.repository.full_name }}
          ref: ${{ github.event.ref }}
        run: |
          [string]$tag = ${env:ref}.Substring(${env:ref}.LastIndexOf('/') + 1)
          [string]$url = 'https://api.github.com/repos/' + ${env:githubFullName} + '/releases/tags/' + ${tag}
          $response={}
          try {
            $response = Invoke-RestMethod -Uri $url -Method Get
          } catch {
            Write-Host "StatusCode:" $_.Exception.Response.StatusCode.value__ 
            Write-Host "StatusDescription:" $_.Exception.Response.StatusDescription
            # 没查到，输出
            echo "::set-output name=needCreateRelease::true"  
            return
          }
          [string]$latestUpUrl = $response.upload_url
          Write-Host 'latestUpUrl:'$latestUpUrl
          if ($latestUpUrl.Length -eq 0) {
            # 没查到，输出
            echo "::set-output name=needCreateRelease::true"  
          }
      # tag 创建github-Release
      - name: createReleaseWin
        id: createReleaseWin
        if: startsWith(github.event.ref, 'refs/tags/') && steps.queryReleaseWin.outputs.needCreateRelease == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1.0.0
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      # 重定向upload_url到环境变量uploadUrl。
      - name: getLatestTagRelease
        # tag 上一步无论成功还是失败都执行
        if: startsWith(github.event.ref, 'refs/tags/')
        shell: pwsh
        env:
          githubFullName: ${{ github.event.repository.full_name }}
          upUrl: ${{ steps.createReleaseWin.outputs.upload_url }}
          ref: ${{ github.event.ref }}
        run: |
          # upUrl不为空，导出就完事
          if (${env:upUrl}.Length -gt 0) {
              $v=${env:upUrl}
              echo "::set-env name=uploadUrl::$v"
              return
          } 
          [string]$tag = ${env:ref}.Substring(${env:ref}.LastIndexOf('/') + 1)
          [string]$url = 'https://api.github.com/repos/' + ${env:githubFullName} + '/releases/tags/' + ${tag}
          $response = Invoke-RestMethod -Uri $url -Method Get
          [string]$latestUpUrl = $response.upload_url
          Write-Host 'latestUpUrl:'$latestUpUrl
          echo "::set-env name=uploadUrl::$latestUpUrl"
          Write-Host 'env uploadUrl:'${env:uploadUrl}
      # tag 上传Release
      - name: uploadRelease
        id: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ env.uploadUrl }}
          asset_path: ./${{ env.packageName }}.zip
          asset_name: ${{ env.packageName }}.zip
          asset_content_type: application/zip